import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { FlagType, GradeRestriction } from '@app/shared';
import { PrismaService } from '../prisma/prisma.service';
import type { CreateFlagDto } from './dto/flag.dto';

/**
 * 前置限定类型 → 等级限制 的固定映射（需求 §7.1）。
 * 此映射是合规硬规则，不可由用户改动。
 */
const FLAG_RESTRICTION: Record<FlagType, GradeRestriction> = {
  [FlagType.ETHICS_ISSUE]: GradeRestriction.FORCE_D, // 严重师德 → 直接 D
  [FlagType.MATERIAL_FRAUD]: GradeRestriction.FORCE_D, // 材料造假 → 直接 D
  [FlagType.STUDENT_SCORE_LOW]: GradeRestriction.NO_S, // 学生分<90 → 不得 S
  [FlagType.RESPONSIBILITY_ACCIDENT]: GradeRestriction.NO_B_OR_ABOVE, // 责任事故 → 不得 B 及以上
  [FlagType.TEACHING_ERROR]: GradeRestriction.NO_A_OR_ABOVE, // 教学差错 → 不得 A 及以上
  [FlagType.DIM_VETO]: GradeRestriction.NO_A_OR_ABOVE, // 维度否决（仅系统自动）
};

@Injectable()
export class FlagService {
  constructor(private prisma: PrismaService) {}

  /** 管理员手工录入前置限定标记（DIM_VETO 只能系统自动产生） */
  async create(adminId: string, dto: CreateFlagDto) {
    if (dto.flagType === FlagType.DIM_VETO) {
      throw new BadRequestException('维度否决由系统自动判定，不可手工录入');
    }
    await this.prisma.user.findUniqueOrThrow({ where: { id: dto.teacherId } });

    // 同教师同学年同类型避免重复
    const exists = await this.prisma.preConditionFlag.findFirst({
      where: {
        teacherId: dto.teacherId,
        academicYear: dto.academicYear,
        flagType: dto.flagType,
      },
    });
    if (exists) {
      throw new BadRequestException('该教师本学年已存在同类型前置限定标记');
    }

    return this.prisma.preConditionFlag.create({
      data: {
        teacherId: dto.teacherId,
        academicYear: dto.academicYear,
        flagType: dto.flagType,
        gradeRestriction: FLAG_RESTRICTION[dto.flagType],
        evidence: dto.evidence,
        confirmedById: adminId,
        isAutoGenerated: false,
      },
    });
  }

  /** 列出某学年所有前置限定（含系统自动的维度否决），附教师名 */
  async list(academicYear?: string) {
    const flags = await this.prisma.preConditionFlag.findMany({
      where: academicYear ? { academicYear } : undefined,
      orderBy: { confirmedAt: 'desc' },
    });
    const ids = [...new Set(flags.map((f) => f.teacherId))];
    const users = await this.prisma.user.findMany({
      where: { id: { in: ids } },
      select: { id: true, name: true },
    });
    const nameMap = new Map(users.map((u) => [u.id, u.name]));
    return flags.map((f) => ({ ...f, teacherName: nameMap.get(f.teacherId) ?? f.teacherId }));
  }

  /** 删除手工标记（系统自动标记不可删，design §7.3） */
  async remove(id: string) {
    const flag = await this.prisma.preConditionFlag.findUnique({ where: { id } });
    if (!flag) throw new NotFoundException('标记不存在');
    if (flag.isAutoGenerated) {
      throw new BadRequestException('系统自动标记（维度否决）不可删除');
    }
    await this.prisma.preConditionFlag.delete({ where: { id } });
    return { ok: true };
  }
}
